android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

android.dependency.useConstraints=true
android.enableAapt2.daemon=true
android.injected.logSender.enable=false
android.nonTransitiveRClass=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.useAndroidX=true
kotlin.code.style=official
org.gradle.configureondemand=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx6144m -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
org.gradle.parallel=true
org.gradle.warning.mode=none
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.country=US
systemProp.user.language=en

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
